global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'metrics-prometheus'
    metrics_path: '/actuator/prometheus' # Configuring the access metrics in application
    honor_labels: false # Allows you to manually control the Prometheus header.
    honor_timestamps: true # Makes prometheus respect the timestamps in the copied data. 
    scheme: http # Configuring the access protocol.
    scrape_interval: 15s
    static_configs:
      - targets: ['spring-observability-app:8080']
        labels:
          application: 'spring-application'